<a href="https://colab.research.google.com/github/hirenpatel-ds/hirenpatel-ds/blob/main/Numpy_arr_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,21)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
arr[5]

5

In [5]:
arr[:11]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
slice_arr = arr[:11]

In [9]:
slice_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
slice_arr[:6] = 25

In [11]:
slice_arr

array([25, 25, 25, 25, 25, 25,  6,  7,  8,  9, 10])

In [12]:
arr

array([25, 25, 25, 25, 25, 25,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [13]:
slice_arr_cpy = slice_arr[:].copy()

In [14]:
slice_arr_cpy

array([25, 25, 25, 25, 25, 25,  6,  7,  8,  9, 10])

In [15]:
slice_arr_cpy[6:] = 50

In [16]:
slice_arr_cpy

array([25, 25, 25, 25, 25, 25, 50, 50, 50, 50, 50])

In [17]:
slice_arr

array([25, 25, 25, 25, 25, 25,  6,  7,  8,  9, 10])

In [19]:
d_arr = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [20]:
d_arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
d_arr[0]

array([ 5, 10, 15])

In [22]:
d_arr[0][1]

10

In [23]:
d_arr[0,1]

10

In [24]:
d_arr[2,2]

45

In [34]:
d_arr[1:,1:]

array([[25, 30],
       [40, 45]])

In [35]:
d_arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
d_arr[1:,:2]

array([[20, 25],
       [35, 40]])

In [45]:
arr = np.arange(0,11)

In [48]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

array([], dtype=bool)